//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeinCottage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeinCottage.Resources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настаняване: след 14.00 ч..
        /// </summary>
        public static string Accomodation {
            get {
                return ResourceManager.GetString("Accomodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави избраните снимки.
        /// </summary>
        public static string AddSelectedPhotos {
            get {
                return ResourceManager.GetString("AddSelectedPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lein Cottage.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заповядайте!.
        /// </summary>
        public static string BeWellcome {
            get {
                return ResourceManager.GetString("BeWellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избери снимка/и.
        /// </summary>
        public static string ChoosePhotos {
            get {
                return ResourceManager.GetString("ChoosePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с. Горно Трапе; общ. Троян; обл. Ловеч..
        /// </summary>
        public static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любомир Пауников.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +359 886 434 795; +359 878 434 796.
        /// </summary>
        public static string ContactPhones {
            get {
                return ResourceManager.GetString("ContactPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string ContactsBtn {
            get {
                return ResourceManager.GetString("ContactsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на снимки.
        /// </summary>
        public static string DeletePhotos {
            get {
                return ResourceManager.GetString("DeletePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/LeinCottageComBG/.
        /// </summary>
        public static string FaceBookLink {
            get {
                return ResourceManager.GetString("FaceBookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    .
        /// </summary>
        public static string FirstHomePageInfo {
            get {
                return ResourceManager.GetString("FirstHomePageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to фейсбук страница.
        /// </summary>
        public static string FooterFaceBookPageLink {
            get {
                return ResourceManager.GetString("FooterFaceBookPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посетете ни и на нашата .
        /// </summary>
        public static string FooterVisit {
            get {
                return ResourceManager.GetString("FooterVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерия.
        /// </summary>
        public static string GalleryBtn {
            get {
                return ResourceManager.GetString("GalleryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string HomeBtn {
            get {
                return ResourceManager.GetString("HomeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на снимки....
        /// </summary>
        public static string PhotoAdding {
            get {
                return ResourceManager.GetString("PhotoAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Освобождаване на стаите: до 11.00 ч..
        /// </summary>
        public static string RoomsRelease {
            get {
                return ResourceManager.GetString("RoomsRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стаите са уютно обзаведени с мека мебел, всички са със самостоятелни бани и повечето са климатизирани. Разполагат с кабелна телевизия и безплатен интернет. Гостите могат да ползват и напълно оборудвана трапезария с кухня, а през лятото да се хранят на верандата на открито..
        /// </summary>
        public static string SecondHomePageInfo {
            get {
                return ResourceManager.GetString("SecondHomePageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На разположение на гостите е голям двор с открит басейн със шезлонги, детски кът и паркинг. Има волейболно игрище и джага..
        /// </summary>
        public static string ThirdHomePageInfo {
            get {
                return ResourceManager.GetString("ThirdHomePageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на снимки.
        /// </summary>
        public static string UploadPhotos {
            get {
                return ResourceManager.GetString("UploadPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при добавянето на снимки!.
        /// </summary>
        public static string UploadPhotosError {
            get {
                return ResourceManager.GetString("UploadPhotosError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, уверете се, че сте избрали изображения и опитайте отново..
        /// </summary>
        public static string UploadPhotosErrorAdvice {
            get {
                return ResourceManager.GetString("UploadPhotosErrorAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връщане в администрацията.
        /// </summary>
        public static string UploadPhotosErrorGoBack {
            get {
                return ResourceManager.GetString("UploadPhotosErrorGoBack", resourceCulture);
            }
        }
    }
}
